<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Admin.WebApi.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.59.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\backend\ruoyu.student\src\Contract\Ruoyu.Study.Student.Contract.csproj" />
  </ItemGroup>

</Project>
