<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Admin.WebApi.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ruoyu.Admin.Common\Ruoyu.Admin.Common.csproj" />
    <ProjectReference Include="..\Ruoyu.Admin.Consul\Ruoyu.Admin.Consul.csproj" />
    <ProjectReference Include="..\Ruoyu.Admin.ServiceClients\Ruoyu.Admin.ServiceClients.csproj" />
  </ItemGroup>

</Project>
